[tool.bumpversion]
current_version = "1.1.2"
commit = true
tag = true
tag_name = "v{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.(?P<build>\\d+))?"
serialize = [
  "{major}.{minor}.{patch}.{build}",
  "{major}.{minor}.{patch}"
]
message = "Version updated from {current_version} to {new_version}"
