on:
  push:
    tags:
    - 'v*'

name: Make Release
jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v5
        with:
            fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
           go-version-file: 'go.mod'
      - name: Build packages
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'amt-certupdater-archive'
          path: |
            ./dist/*.zip
            ./dist/*.tar.gz
            ./dist/*.apk
            ./dist/*.deb
          if-no-files-found: error
  upload-to-repo:
    name: Upload Apk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: 'amt-certupdater-archive'
          path: dist
      - name: Move apks
        run: |
          set -ex
          mkdir -p pkgs/
          for x in dist/*.apk; do cp $x pkgs/$(basename $x | sed s/_/-/g | sed s/-x86-64\.apk/-x86_64.apk/ ); done
          for x in dist/*.deb; do cp $x pkgs/; done
      - name: Push to apk repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.REGISTRY_SSH_KEY }}
        with:
          source-directory: 'pkgs'
          destination-github-username: 'KalleDK'
          destination-repository-name: 'registry'
          user-email: apk@k-moeller.dk
          target-branch: repo
          target-directory: pkgs/amt-certupdater
  